[application]
  basedir = 'data'

  [application.log]
    interval = 5000

  [application.rebalance]
    interval = 10
    loglevel = 1

  [application.option]
    vectorization = 'vector'

[[diagnostic]]
  name = 'history'
  interval = 100

[[diagnostic]]
  name = 'resource'
  interval = 10
  node = 'stats'
  rank = 'stats'

[[diagnostic]]
  name = 'field'
  interval = 100

[[diagnostic]]
  name = 'particle'
  fraction = 1.0
  interval = 1000

[parameter]
  Nx = 1024
  Ny = 1
  Nz = 1
  Cx = 64
  Cy = 1
  Cz = 1
  Ns = 2
  wp = 1.0
  delt = 0.05
  delh = 0.1
  nppc = 32
  mime = 25
  u0 = 0.1
  phi = 0.0
  theta = 90.0
  sigma = 0.04
  betae = 0.5
  betai = 0.5
  taper = 10.0
