[application]
  basedir = 'data'

  [application.log]
    interval = 10

  [application.rebalance]
    interval = 10

  [application.option]
    vectorization = 'vector'

[[diagnostic]]
  name = 'history'
  interval = 10

[[diagnostic]]
  name = 'field'
  interval = 20

[[diagnostic]]
  name = 'particle'
  interval = 200

[parameter]
  Nx = 768
  Ny = 2
  Nz = 2
  Cx = 96
  Cy = 1
  Cz = 1
  Ex = 0.0
  Ey = 0.0
  Ez = 0.0
  Bx = 5.0
  By = 0.0
  Bz = 0.0
  Ns = 2
  cc = 10.0
  delt = 0.05
  delh = 1.0

[[parameter.particle]]
    np = 10
    qm = -1.0
    ro = 1.0
    vt = 1.0

[[parameter.particle]]
    np = 10
    qm = +0.1
    ro = 10.0
    vt = 0.31622776601
